<<<<<<< HEAD
name: Run Locust Tests on Commit
  on:
    push:
      branches:
        - main
jobs:
  locust-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: â€™3.10â€™
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ............
      - name: Start Flask server
        run: |
          ............ &
          echo "Waiting for Flask server to start"
          sleep 30
=======

>>>>>>> 5a738982f924f8c8158b6dd9889fdeb63eaeda20
